// ╔══════════════════════════════════════════════════════════╗
// ║  Source Generator: AutoToStringGenerator                ║
// ║  Generates ToString() methods for [AutoToString] types  ║
// ║  Theme: 9 — Compiler & Tooling                          ║
// ╚══════════════════════════════════════════════════════════╝
//
// This is an incremental source generator (IIncrementalGenerator)
// that finds classes decorated with [AutoToString] and generates
// a ToString() override listing all public properties.
//
// GOING DEEPER:
// Incremental generators (introduced in .NET 6) replaced the
// original ISourceGenerator API. The key difference: incremental
// generators use a pipeline model that caches intermediate results,
// so only changed files trigger regeneration. This makes them
// fast enough for real-time IDE feedback.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace DevScripts.Generators;

/// <summary>
/// An incremental source generator that produces ToString() methods
/// for types decorated with <c>[AutoToString]</c>.
/// </summary>
[Generator]
public sealed class AutoToStringGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The name of the attribute that triggers generation.
    /// </summary>
    private const string AttributeName = "AutoToString";
    private const string AttributeFullName = "DevScripts.Models.AutoToStringAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Find all class/struct declarations with [AutoToString]
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateType(node),
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        // Step 2: Combine with compilation and generate
        context.RegisterSourceOutput(classDeclarations,
            static (spc, typeInfo) => GenerateToString(spc, typeInfo));
    }

    /// <summary>
    /// Quick syntactic check: is this a class/struct with any attribute?
    /// This runs on every keystroke so it must be fast.
    /// </summary>
    private static bool IsCandidateType(SyntaxNode node) =>
        node is TypeDeclarationSyntax typeDecl &&
        typeDecl.AttributeLists.Count > 0;

    /// <summary>
    /// Semantic check: does this type have the [AutoToString] attribute?
    /// This runs only for candidates, so it can be more thorough.
    /// </summary>
    private static TypeToGenerate? GetTypeInfo(GeneratorSyntaxContext context)
    {
        var typeDecl = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;

        if (symbol is null) return null;

        // Check for the AutoToString attribute
        var hasAttribute = symbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);

        if (!hasAttribute) return null;

        // Collect public properties
        var properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                        !p.IsStatic &&
                        !p.IsIndexer)
            .Select(p => p.Name)
            .ToImmutableArray();

        // Collect containing type hierarchy for nested types
        var containingTypes = ImmutableArray.CreateBuilder<ContainingTypeInfo>();
        var containingType = symbol.ContainingType;
        while (containingType is not null)
        {
            containingTypes.Insert(0, new ContainingTypeInfo(
                containingType.Name,
                containingType.IsValueType,
                containingType.IsRecord,
                containingType.IsStatic));
            containingType = containingType.ContainingType;
        }

        return new TypeToGenerate(
            Namespace: symbol.ContainingNamespace?.ToDisplayString() ?? "",
            TypeName: symbol.Name,
            Properties: properties,
            IsValueType: symbol.IsValueType,
            ContainingTypes: containingTypes.ToImmutable());
    }

    /// <summary>
    /// Generates the ToString() method for a type.
    /// </summary>
    private static void GenerateToString(SourceProductionContext context, TypeToGenerate type)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by AutoToStringGenerator");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(type.Namespace))
        {
            sb.AppendLine($"namespace {type.Namespace};");
            sb.AppendLine();
        }

        var indent = "";

        // Open containing type wrappers for nested types
        foreach (var ct in type.ContainingTypes)
        {
            var ctKeyword = ct.IsValueType ? "struct" : "class";
            var ctStatic = ct.IsStatic ? "static " : "";
            sb.AppendLine($"{indent}{ctStatic}partial {ctKeyword} {ct.Name}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        var typeKeyword = type.IsValueType ? "struct" : "class";
        sb.AppendLine($"{indent}partial {typeKeyword} {type.TypeName}");
        sb.AppendLine($"{indent}{{");

        // Build the ToString interpolated string
        sb.Append($"{indent}    public override string ToString() => $\"{type.TypeName} {{{{ ");

        for (var i = 0; i < type.Properties.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{type.Properties[i]} = {{{type.Properties[i]}}}");
        }

        sb.AppendLine(" }}\";");
        sb.AppendLine($"{indent}}}");

        // Close containing type wrappers
        for (var i = type.ContainingTypes.Length - 1; i >= 0; i--)
        {
            indent = new string(' ', i * 4);
            sb.AppendLine($"{indent}}}");
        }

        var fileName = type.ContainingTypes.Length > 0
            ? $"{string.Join(".", type.ContainingTypes.Select(ct => ct.Name))}.{type.TypeName}.g.cs"
            : $"{type.TypeName}.g.cs";

        context.AddSource(
            fileName,
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>Data about a type that needs ToString generation.</summary>
    private sealed record TypeToGenerate(
        string Namespace,
        string TypeName,
        ImmutableArray<string> Properties,
        bool IsValueType,
        ImmutableArray<ContainingTypeInfo> ContainingTypes);

    /// <summary>Data about a containing type wrapper.</summary>
    private sealed record ContainingTypeInfo(
        string Name,
        bool IsValueType,
        bool IsRecord,
        bool IsStatic);
}
