// Chapter 10 — Compiler & Tooling Integration — INTERMEDIATE
// ----------------------------------------------------------------
// Exercise: Add a second attribute, [AutoEquals], to
//   DevScripts.Generators. When applied to a class, the generator
//   should emit an override of Equals(object?) and GetHashCode()
//   that compares all public properties for value equality.
//   Decorate ServerInfo with both [AutoToString] and [AutoEquals]
//   and verify both generated partials compile and work.
//
// Hint: The pipeline shape from AutoToStringGenerator copies over;
//   only the code-generation step is different. Use HashCode.Combine
//   for GetHashCode.
// ----------------------------------------------------------------
//
// IMPORTANT — Why this file does NOT host the actual generator:
// ---------------------------------------------------------------
// A Roslyn IIncrementalGenerator must live in a SEPARATE csproj
// that targets netstandard2.0 (or another modern TFM controlled
// by the build host) and references Microsoft.CodeAnalysis.CSharp.
// It is wired into the consuming project via
//   <ProjectReference OutputItemType="Analyzer" .../>.
//
// That extra project would balloon the Exercises solution from 11
// projects to 12 plus a second TFM hop. Instead, this file shows
// the SHAPE the generator should emit (a hand-written sample of
// the partial halves it would produce) and a one-line `[AutoEquals]`
// attribute declaration. The accompanying appendix entry walks
// through the actual IIncrementalGenerator code as prose + a
// commentary callout pointing at DevScripts/AutoToStringGenerator.cs
// in the companion CodeSample repo for the working template.

namespace KeepUpCs.Exercises.Ch10;

[AttributeUsage(AttributeTargets.Class)]
public sealed class AutoToStringAttribute : Attribute { }

[AttributeUsage(AttributeTargets.Class)]
public sealed class AutoEqualsAttribute : Attribute { }

// ── The class a real generator would extend ─────────────────────
[AutoToString, AutoEquals]
public sealed partial class ServerInfo
{
    public required string Host    { get; init; }
    public required int    Port    { get; init; }
    public required string Region  { get; init; }
    public required bool   UseTls  { get; init; }
}

// ── The hand-written equivalent of what the generator would emit ─
// In the real generator this would live in
// obj/Debug/net10.0/generated/.../AutoEqualsGenerator/ServerInfo.AutoEquals.g.cs
public partial class ServerInfo
{
    // Generated by [AutoToString]
    public override string ToString() =>
        $"ServerInfo {{ Host={Host}, Port={Port}, Region={Region}, UseTls={UseTls} }}";

    // Generated by [AutoEquals]
    public override bool Equals(object? other) =>
        other is ServerInfo o &&
        Host   == o.Host   &&
        Port   == o.Port   &&
        Region == o.Region &&
        UseTls == o.UseTls;

    public override int GetHashCode() =>
        HashCode.Combine(Host, Port, Region, UseTls);

    public static bool operator ==(ServerInfo? a, ServerInfo? b) => Equals(a, b);
    public static bool operator !=(ServerInfo? a, ServerInfo? b) => !Equals(a, b);
}

public static class IntermediateDemo
{
    public static void Run()
    {
        Console.WriteLine("Ch10 Intermediate — [AutoToString] + [AutoEquals] generator shape");
        Console.WriteLine(new string('─', 60));

        var a = new ServerInfo { Host = "api-east", Port = 443, Region = "us-east-1", UseTls = true };
        var b = new ServerInfo { Host = "api-east", Port = 443, Region = "us-east-1", UseTls = true };
        var c = new ServerInfo { Host = "api-west", Port = 443, Region = "us-west-2", UseTls = true };

        Console.WriteLine($"  a = {a}");
        Console.WriteLine($"  b = {b}");
        Console.WriteLine($"  c = {c}");
        Console.WriteLine($"  a.Equals(b)?   {a.Equals(b)}    (same data → true)");
        Console.WriteLine($"  a.Equals(c)?   {a.Equals(c)}    (different host → false)");
        Console.WriteLine($"  HashCode(a) == HashCode(b)? {a.GetHashCode() == b.GetHashCode()}");

        Console.WriteLine();
        Console.WriteLine("  See the appendix entry for the IIncrementalGenerator implementation");
        Console.WriteLine("  that would emit this Equals/GetHashCode partial automatically.");
    }
}
